services:
    postgres:
        image: postgres:18
        environment:
            POSTGRES_DB: demo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports: 
            - "5432:5432"
        volumes: 
            - "postgres_data:/var/lib/postgresql"
        networks:
            devapp:
    
    app:
        build: 
            context: .
        depends_on: 
            - postgres
        environment:
            - ConnectionStrings__Default=Host=postgres;Database=demo;Username=postgres;Password=postgres
        ports: ["5000:80"]
        volumes:
            - ./:/app
            - ~/.nuget:/home/ubuntu/.nuget
        tty: true
        networks:
            devapp:

volumes:
    postgres_data:

networks:
    devapp: