### Info
GET http://localhost:5000/

### List pizzas
GET http://localhost:5000/pizzas

### Add pizza
POST http://localhost:5000/pizzas
Content-Type: application/json

{
    "id": 20,
    "name": "Africana",
    "size": "Large",
    "price": "23.18"
}

### Remove pizza
DELETE http://localhost:5000/pizzas/20

